### PR TITLE
Update Data_Viz.ipynb

### PR DESCRIPTION
**Pull request by Drake-Eidukas**
fixed spelling

### CODE REVIEW

**Comment by tyler-thetyrant** [comment]
can you not

**Comment by bcongdon** [comment]
🔥

**Comment by tyler-thetyrant** [comment]
triggered

**Comment by Drake-Eidukas** [comment]
This is my strategy for being a contributor to some big, open source project, just practicing here ;)

**Comment by tyler-thetyrant** [comment]
here you go: 
https://github.com/numpy/numpy/issues

**Comment by Drake-Eidukas** [comment]
:(

**Pull request closed without merging**
